### ISSUE TITLE
Middleware question

### ISSUE THREAD

**Issue by chemoish** [ForbesLindesay/redux-wait#3]
https://github.com/ForbesLindesay/redux-wait#2-ensure-all-middleware-returns-a-promise-or-runs-synchronously

Could you elaborate a bit more on how this part works?

I am trying to understand how, after a bunch of promises (perhaps in nested components) fire, does the UI rendering block until they are all complete.

Regards,

**Comment by ForbesLindesay** [comment]
The UI rendering doesn't block.  Each time an action is fired, we wait until the action has been processed (potentially asynchronously) then re-render the UI.

**Comment by chemoish** [comment]
Maybe I am just not following the src code on why this is bad…

``` js
// action creator
function loadUser(login) {
  return (dispatch, getState) => {
    const user = getState().entities.users[login];
    if (user) {
      return null;
    }

    $.getJson('/user/' + login, function (data) {
      // The server won't wait for this action :(
      dispatch({type: 'LOADED_USER', user: data});
    });
  };
}
```

Also, I didn't quite follow the the `src/index.js` implementation of collecting promises. And how/if they are **all** being collected before returning `renderToString`'s `Promise`.

(I assume there is something to it since there is a pending counter)

**Comment by ForbesLindesay** [comment]
Given that action creator, there is no way for redux-wait to tell if the action has been completed.  By reading the code, I can tell that it sometimes dispatches no actions, and sometimes dispatches an action asynchronously.  redux-wait doesn't know that though, and even if it did, how would it know whether (for a given example) `loadUser` was going to fire 0 or 1 actions?

redux-wait makes the assumption that once middleware returns (and if the function returns a promise, once that promise is fulfilled), no more actions will be fired.  In the example of `redux-thunk`, the function returns as soon as your action-creator has finished executing, so you must dispatch actions immediately.

If you instead make `loadUser` look like:

``` js
function loadUser(login) {
  return {type: 'LOAD_USER', login: login};
}
```

You can then actually load the user in middleware:

``` js
function userLoadingMiddleware({ dispatch }) {
  return next => action => {
    dispatch(action);
    if (action.type !== 'LOAD_USER') return;
    // because we return a promise, the server knows to wait for it
    return getJson('/user/' + login).then(function (data) {
      dispatch({type: 'LOADED_USER', user: data});
    });
  };
}
```

Because our action creators always have clear, deterministic behaviour, redux-wait knows when they're done.  If our userLoadingMiddleware is going to do more work, it returns a `Promise` to indicate when it's done.

**Comment by chemoish** [comment]
I guess it just depends what is going to handle the promise and how that is going to be checked.

I still don't quite follow the reasoning behind requiring the middleware to create the promise rather than the action. In either situation you can catch the promise in a middleware and return it.

> // because we return a promise, the server knows to wait for it

I was more so trying to figure out how this worked and how it interfaced with nested components and nested loading.

Anyways thanks for the insight.

**Comment by ForbesLindesay** [comment]
> how it interfaced with nested components 

Because middleware is not nested.  The middleware is just a simple list, and by using `redux-wait` instead of applyMiddleware, we get to intercept every middleware function, allowing us to get a copy of every promise, in order to wait for it.

If a promise is used in a random location, we have no way of knowing about it.  It doesn't matter where the promise is created, but if it's not returned by some middleware, redux-wait will have no way of knowing it exists, and thus no way of waiting for it.

**Comment by chemoish** [comment]
Ok I think i get the premise.
1. Server render compiles a page—fires actions
2. Some/all of actions return promises
3. The `redux-wait` store enhancer thingy manages those middleware to check the return value and then collects the promises.
4. The store attempts to renderToString on every action (Checking the promise list each time).

**Comment by ForbesLindesay** [comment]
Yes, that's about right.
